### ISSUE TITLE
Allow cygin version selection

### ISSUE THREAD

**Issue by PipeItToDevNull** [vegardit/cygwin-portable-installer#15]
Per these issues [cmder](https://github.com/cmderdev/cmder/issues/2241) and [ConEmu](https://github.com/Maximus5/ConEmu/issues/1966)

The latest version of cygwin cannot work with ConEmu/cmder. Can the ability to choose a version of cygwin to install be added to this script.

**Comment by 0zhu** [comment]
1. Choosing Cygwin version [is not supported by Cygwin CLI installer](https://cygwin.com/faq/faq.html#faq.setup.cli).
2. The problem related to bugs while displaying commands output should be observed only when running Cygwin via standard Windows console. Things get better when running Cygwin via [Cygwin connector](https://conemu.github.io/en/CygwinMsysConnector.html), however I still notice different bugs with connector (for instance, arrow key do not work in vim). Everything is working fine with [Mintty](https://mintty.github.io/).
3. The latest installer versions from vegardit use Cygwin connector as default task, so I assume you use some old version where Cygwin is run via Windows console (or your own ConEmu task).

So in order to resolve the problem:
**1**. Using current Cygwin portable installer (switch terminal to Mintty):
- ConEmu > Settings > Tasks> + button
- Name:
```
CygWin::Mintty
```
- check `Default task for new console`
- Commands:
```
"%ConEmuDir%\..\cygwin\bin\mintty.exe" -o FontHeight=10 -o AllowBlinking=yes -o CopyOnSelect=yes -o RightClickAction=paste -o Transparency=off -o ConfirmExit=no - -cur_console:pm:"/cygdrive":P:"<xterm>"
```

OR

**2**. Try [Mobaxterm](https://mobaxterm.mobatek.net/) (in case you do not use local ansible package installed in Cygwin).
It uses a different terminal and old Cygwin core.
